pub mod agent;
pub mod api;
pub mod cli;
pub mod config;
pub mod mcp;
pub mod models;
pub mod storytelling;
pub mod voice_id;

#[cfg(feature = "gui")]
pub mod app;
#[cfg(feature = "gui")]
pub mod audio;
#[cfg(feature = "gui")]
pub mod file_manager;
#[cfg(feature = "gui")]
pub mod fonts;
#[cfg(feature = "gui")]
pub mod multi_speech;
#[cfg(feature = "gui")]
pub mod timeline;
